CREATE TABLE [dbo].[RF_DWH_SCHEDULE] (
    [schedule_id]                 INT             IDENTITY (1, 1) NOT NULL,
    [line_facility_id]            INT             NOT NULL,
    [shift_id]                    INT             NOT NULL,
    [item_id]                     INT             NOT NULL,
    [per]                         INT             NOT NULL,
    [qty]                         INT             NULL,
    [schedule_date]               DATETIME        NOT NULL,
    [inserted_date]               DATETIME        NOT NULL,
    [inserted_by]                 VARCHAR (50)    NOT NULL,
    [modified_date]               DATETIME        NULL,
    [modified_by]                 VARCHAR (50)    NULL,
    [deleted_date]                DATETIME        NULL,
    [deleted_by]                  VARCHAR (50)    NULL,
    [seq_no]                      INT             NULL,
    [start_time]                  DATETIME        NULL,
    [end_time]                    DATETIME        NULL,
    [act_qty]                     INT             NULL,
    [item_product_variation_id]   INT             NULL,
    [comment]                     VARCHAR (1000)  NULL,
    [production_comment]          VARCHAR (1000)  NULL,
    [production_start_time]       DATETIME        NULL,
    [production_end_time]         DATETIME        NULL,
    [production_line_facility_id] INT             NULL,
    [isproductionchanged]         BIT             NULL,
    [ncrewplaning]                NUMERIC (18, 2) NULL,
    [nspeedplaning]               NUMERIC (18, 2) NULL,
    [nlinehrsplaning]             NUMERIC (18, 2) NULL,
    [ncrewproduction]             NUMERIC (18, 2) NULL,
    [nspeedproduction]            NUMERIC (18, 2) NULL,
    [nlinehrsproduction]          NUMERIC (18, 2) NULL,
    [nitemseqplaning]             INT             NULL,
    [nitemseqproduction]          INT             NULL,
    [seq_no_prod]                 INT             NULL,
    [re_run_planing]              INT             NULL,
    [over_run_planing]            INT             NULL,
    [break_use_planing]           BIT             NULL,
    [lunch_use_planing]           BIT             NULL,
    [re_run_production]           INT             NULL,
    [over_run_production]         INT             NULL,
    [break_use_production]        BIT             NULL,
    [lunch_use_production]        BIT             NULL,
    [crew_size_actual_planing]    INT             NULL,
    [crew_size_actual_production] INT             NULL,
    [production_createdby]        VARCHAR (50)    NULL,
    [production_modifiedby]       VARCHAR (50)    NULL,
    [status_id]                   INT             NULL,
    CONSTRAINT [PK_RF_DWH_SCHEDULE] PRIMARY KEY CLUSTERED ([schedule_id] ASC),
    CONSTRAINT [FK_RF_DWH_SCHEDULE_RF_DWH_SCHEDULE] FOREIGN KEY ([line_facility_id]) REFERENCES [dbo].[RF_DWH_XREF_LINE_FACILITY] ([line_facility_id]),
    CONSTRAINT [FK_RF_DWH_SCHEDULE_RF_DWH_SHIFT] FOREIGN KEY ([shift_id]) REFERENCES [dbo].[RF_DWH_SHIFT] ([shift_id])
);

