CREATE TABLE [dbo].[XREF_ITEM_PRODUCT_VARIATION] (
    [item_product_variation_id] INT             IDENTITY (1, 1) NOT NULL,
    [applecore_product_id]      INT             NOT NULL,
    [applecore_variation_id]    INT             NOT NULL,
    [variation_id]              INT             NOT NULL,
    [pro_seal_twin_crew]        INT             NULL,
    [pro_seal_twin_t_max]       DECIMAL (18, 4) NULL,
    [pro_seal_single_crew]      INT             NULL,
    [pro_seal_single_t_max]     DECIMAL (18, 4) NULL,
    [over_wrap_crew]            INT             NULL,
    [over_wrap_t_max]           DECIMAL (18, 4) NULL,
    [table_crew]                INT             NULL,
    [table_t_max]               DECIMAL (18, 4) NULL,
    [bulk_crew]                 INT             NULL,
    [bulk_t_max]                DECIMAL (18, 4) NULL,
    [play_book]                 VARCHAR (1000)  NULL,
    [category_id]               INT             NULL,
    [twin_build_grade_id]       INT             NULL,
    [single_build_grade_id]     INT             NULL,
    [flow_build_grade_id]       INT             NULL,
    [table_build_grade_id]      INT             NULL,
    [inserted_date]             DATETIME        NULL,
    [inserted_by]               VARCHAR (50)    NULL,
    [modified_date]             DATETIME        NULL,
    [modified_by]               VARCHAR (50)    NULL,
    [deleted_date]              DATETIME        NULL,
    [deleted_by]                VARCHAR (50)    NULL,
    [default_line_id]           INT             NULL,
    CONSTRAINT [PK_XREF_ITEM_PRODUCT_VARIATION] PRIMARY KEY CLUSTERED ([item_product_variation_id] ASC),
    CONSTRAINT [FK_XREF_ITEM_PRODUCT_VARIATION_RF_DWH_VARIATION_MASTER] FOREIGN KEY ([variation_id]) REFERENCES [dbo].[RF_DWH_VARIATION_MASTER] ([variation_id]),
    CONSTRAINT [applecore_variation_id_unique] UNIQUE NONCLUSTERED ([applecore_variation_id] ASC, [deleted_date] ASC),
    CONSTRAINT [Applecore_VariationID_ID_Unique] UNIQUE NONCLUSTERED ([applecore_variation_id] ASC, [deleted_date] ASC),
    CONSTRAINT [ProductID_VariationID] UNIQUE NONCLUSTERED ([applecore_product_id] ASC, [variation_id] ASC, [deleted_date] ASC)
);

