CREATE TYPE [dbo].[ImportExcelTableType] AS TABLE (
    [applecore_product_id]   INT             NULL,
    [applecore_variation_id] INT             NULL,
    [productname]            VARCHAR (MAX)   NULL,
    [variation_nm]           VARCHAR (MAX)   NULL,
    [pro_seal_twin_crew]     INT             NULL,
    [pro_seal_twin_t_max]    DECIMAL (18, 4) NULL,
    [pro_seal_single_crew]   INT             NULL,
    [pro_seal_single_t_max]  DECIMAL (18, 4) NULL,
    [over_wrap_crew]         INT             NULL,
    [over_wrap_t_max]        DECIMAL (18, 4) NULL,
    [table_crew]             INT             NULL,
    [table_t_max]            DECIMAL (18, 4) NULL,
    [bulk_crew]              INT             NULL,
    [bulk_t_max]             DECIMAL (18, 4) NULL,
    [play_book]              VARCHAR (MAX)   NULL,
    [category_id]            VARCHAR (MAX)   NULL,
    [twin_build_grade_id]    VARCHAR (50)    NULL,
    [single_build_grade_id]  VARCHAR (50)    NULL,
    [flow_build_grade_id]    VARCHAR (50)    NULL,
    [table_build_grade_id]   VARCHAR (50)    NULL,
    [default_line]           VARCHAR (500)   NULL);

