CREATE LOGIN [RevFoodsWebCR]
    WITH PASSWORD = N'Kkwaoy7rL+r=qf_hrd{lqrKqmsFT7_&#$!~<ALweblbQs3f$', SID = 0x0AD2EB90EA7F684CAC4D11587B0EF93E, DEFAULT_DATABASE = [RevFoodsWebCR], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

